### ISSUE TITLE
Building problems

### ISSUE THREAD

**Issue by IceandFire04** [Patoke/re-plants-vs-zombies#12]
Collected a list of bugs with the game built from the source of the `sexy-vk` branch:
- Zen Garden Crashes
- No yellow background behind tooltips
- Seeing Stars crashes with no error message
- Imitater crashes when selecting him
I would try to fix these although I don't know nearly enough C++ to try and solve these

**Comment by minerscale** [comment]
Hi! Try my branch at https://github.com/minerscale/re-plants-vs-zombies/ on the main branch.

It's much much further finished than this one. I think all of your bugs are fixed!

**Comment by IceandFire04** [comment]
Alright! I'll check it out and get back ASAP!

**Comment by IceandFire04** [comment]
So it seems like I need sdl although I the files I put in don't work and cmake fails. It looks like it's trying to find it in the `external` folder but nothing is generated, nor was the folder there when I tried this repo. Anything I could do?

**Comment by minerscale** [comment]
Yes,

We've been screwing with the build system, delete your build/ folder and reconfigure a clean build. Do this as a troubleshooting step when using new versions.

Pull my repo again up to the latest commit also if it's not. Let me know if it works.

**Comment by IceandFire04** [comment]
It still says I need SDL although I don't know what files to give it. At least I did get further this time!

**Comment by minerscale** [comment]
hmm, try deleting your local copy and redownloading my repo in (I just recently completely broke parity with this repo with a git filter-branch for various reasons).

You'll have to give me a bit more info if that doesn't work because I'm at a bit of a loss! Once you have it built you'll have to copy your properties/ folder and the main.pak file into the same directory as the build executable and run it. (and bass.dll/bass.so as well). A good troubleshooting step would be to send me the error that you're actually facing.

**Comment by IceandFire04** [comment]
yeah, I can imagine the error would be helpful! here it is:
`1> [CMake] CMake Error at src/framework/CMakeLists.txt:117 (target_link_libraries):
1> [CMake]   Target "PlantsVsZombies" links to:
1> [CMake] 
1> [CMake]     SDL2::SDL2-static
1> [CMake] 
1> [CMake]   but the target was not found.  Possible reasons include:
1> [CMake] 
1> [CMake]     * There is a typo in the target name.
1> [CMake]     * A find_package call is missing for an IMPORTED target.
1> [CMake]     * An ALIAS target is missing.`
I don't think there is an installable version of SDL like there is for Vulkan because all I can find is the DLL.

**Comment by minerscale** [comment]
SDL should be compiled from source and linked straight in! I'm very confused.

I've pushed a change that hopefully makes SDL compile a static library.. even though it already does on my machine. Pull my code again and try a rebuild. (and just for a sanity check we're talking the main branch on https://github.com/minerscale/re-plants-vs-zombies/)

 Can you give me the following info?

OS, compiler, IDE (if any), any other development environment information you think might be important.

Thanks,
Aaron.

**Comment by IceandFire04** [comment]
OS: Windows 11 preview
Compiler: Ninja
IDE: MSVC

**Comment by IceandFire04** [comment]
Here's the `external` folder it generates if it helps:
[external.zip](https://github.com/Patoke/re-plants-vs-zombies/files/14310483/external.zip)

**Comment by IceandFire04** [comment]
As a temporary fix provide the `external` folder it generated on your computer in the repo somewhere like in a zip, whatever works

**Comment by IceandFire04** [comment]
It turns out it was a Visual Studio error! I just updated VS and it ended up working just like that!

**Comment by Gostavo2003** [comment]
Can you add me on Discord @MrNooberDude ?

Username: Gostavo.2003

**Comment by IceandFire04** [comment]
This was fixed a while ago, plus I'm using the original release version source now
