### ISSUE TITLE
Font loading problems in sexy-vk branch

### ISSUE THREAD

**Issue by engineergamingistaking** [Patoke/re-plants-vs-zombies#15]
When I try to debug the game, the console prints out this:

FATAL ERROR: Font Descriptor Error in data/BrianneTod16.txt
Unknown Command on Line 101:

FATAL ERROR: Failed to load font: data/BrianneTod16.txt

I have the game files for Plants vs. Zombies in the out/build/x64-Debug directory, what could be causing this?

**Comment by engineergamingistaking** [comment]
Never mind.

**Comment by Patoke** [comment]
Hello Thomas, if possible please describe how you fixed your issue so if someone else also has the same problem they have a way to fix it.

Best regards!

**Comment by engineergamingistaking** [comment]
> Hello Thomas, if possible please describe how you fixed your issue so if someone else also has the same problem they have a way to fix it.
> 
> Best regards!

I never managed to fix it actually. I accidentally close this because I moved on, but I'm back now. Anyways, when the game tries to load the BrianneTod16.txt it detects a Unknown Command on Line 101, and I don't know what it's talking about.

**Comment by engineergamingistaking** [comment]
Closing this issue, I'm not worried about this anymore

**Comment by SuperPWNAGETHOMAS69** [comment]
Reopening this actually. I'm interested in this project again.
