### ISSUE TITLE
building issue

### ISSUE THREAD

**Issue by ghost** [Patoke/re-plants-vs-zombies#16]
when i try to run "cmake -G Ninja -B build" on the sexy-vk branch, this happens

"-- The C compiler identification is unknown
-- The CXX compiler identification is unknown
CMake Error at CMakeLists.txt:8 (project):
  No CMAKE_C_COMPILER could be found.

  Tell CMake where to find the compiler by setting either the environment
  variable "CC" or the CMake cache entry CMAKE_C_COMPILER to the full path to
  the compiler, or to the compiler name if it is in the PATH.

CMake Error at CMakeLists.txt:8 (project):
  No CMAKE_CXX_COMPILER could be found.

  Tell CMake where to find the compiler by setting either the environment
  variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
  to the compiler, or to the compiler name if it is in the PATH.

-- Configuring incomplete, errors occurred!"

**Comment by minerscale** [comment]
Sorry it took so long to get to you!

It looks like your build system is not sane. This isn't an issue with this project but rather the environment you set up to try compiling it. C/C++ projects are a pain and take a little set up to get going. I don't know anything about what system you're using so I can only guess but I imagine you don't have a C/C++ compiler installed. Try installing Clang or GCC on your computer and try again.

The configure step may fail again once you fix that error. In that case you should first try googling the errors as many of them are quite common horrors when first setting up a working build environment.

Thanks for your interest!
