### ISSUE TITLE
Can Anyone for god's sake provide the build ?

### ISSUE THREAD

**Issue by Gostavo2003** [Patoke/re-plants-vs-zombies#17]
I've spent like 7 hours trying to compile the source code…
Can you guys please provide it ?

**Comment by Patoke** [comment]
Hello,

Legally, we can't provide pre-built binaries of our project.

Best regards!

**Comment by Gostavo2003** [comment]
> Hello,
> 
> Legally, we can't provide pre-built binaries of our project.
> 
> Best regards!

Can I contact you on discord ? Please ?

**gostavo.2003**
