### ISSUE TITLE
Contact Information?

### ISSUE THREAD

**Issue by ps5fanohyeah** [Patoke/re-plants-vs-zombies#6]
ive been working with a older decomp, and just saw this now.
is there any way i can contact you? it would be neat to discuss this decompile. i may have some fixes too if they arent already fixed, but im just building as i type this.

i mostly use discord, "spaghetto207".

**Comment by minerscale** [comment]
That's fantastic! It's always great to hear people are interested in the project. I will contact on Discord.

What fun,
Aaron.

**Comment by Sumandora** [comment]
@minerscale mind contacting me too? (discord: 48_8b_45_08)

**Comment by Patoke** [comment]
Sup man, I've sent you a friend request on discord right now, as Aaron already mentioned, it's always great to hear that more and more people are interested in the project!

Best regards,
Patoke.
