### ISSUE TITLE
Cmake build failing

### ISSUE THREAD

**Issue by Vali-98** [Patoke/re-plants-vs-zombies#9]
As stated in the build steps, the following command is run:

`cmake --build cmake-build`

This however results in a build failure:

```
Looking for a ASM_NASM compiler failed with the following output:
-- The ASM_NASM compiler identification is unknown
-- Didn't find assembler
CMake Error at CMakeLists.txt:2 (project):
  No CMAKE_ASM_NASM_COMPILER could be found.

  Tell CMake where to find the compiler by setting either the environment
  variable "ASM_NASM" or the CMake cache entry CMAKE_ASM_NASM_COMPILER to the
  full path to the compiler, or to the compiler name if it is in the PATH.

```

I have defined `ASM_NASM` in my environment variables.

This was tested in both Visual Studio and Visual Studio Code

**Comment by minerscale** [comment]
As a sanity check, do you have nasm (netwide assembler) installed? And if you have it installed, can it target 64 bit architectures?

I'm not actually sure what nasm is needed for in the build process but I would imagine that it's for SDL_Image for some of the image processing SIMD.

Apologies about the largely useless question but I don't run windows and am at a bit of a loss as to how to proceed. I don't think it's an issue with the build configuration though.

**Comment by minerscale** [comment]
closed for lack of activity, not enough information.
